// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaWallet.Infrastructure.Persistence;

#nullable disable

namespace NovaWallet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NovaWalletDbContext))]
    [Migration("20260916155018_ChangedAuditToAccept0Amount")]
    partial class ChangedAuditToAccept0Amount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovaWallet.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorCustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceAfterKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceBeforeKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("AuditLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_AmountKobo_Positive", "[AmountKobo] >= 0");

                            t.HasCheckConstraint("CK_AuditLogs_BalanceAfterKobo_NonNegative", "[BalanceAfterKobo] >= 0");

                            t.HasCheckConstraint("CK_AuditLogs_BalanceBeforeKobo_NonNegative", "[BalanceBeforeKobo] >= 0");
                        });
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.DailyTransferLimit", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WatDate")
                        .HasColumnType("date");

                    b.Property<long>("OutboundTotalKobo")
                        .HasColumnType("bigint");

                    b.HasKey("WalletId", "WatDate");

                    b.ToTable("DailyTransferLimits", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyTransferLimits_OutboundTotalKobo_NonNegative", "[OutboundTotalKobo] >= 0");
                        });
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.FinancialLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FinancialLimits", null, t =>
                        {
                            t.HasCheckConstraint("CK_FinancialLimits_AmountKobo_Positive", "[AmountKobo] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountKobo = 50000000L,
                            Code = "DAILY_OUTBOUND_TRANSFER",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResponseBodyJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CustomerId", "Endpoint", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceAfterKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WalletId", "CreatedAtUtc");

                    b.ToTable("LedgerEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_LedgerEntries_AmountKobo_Positive", "[AmountKobo] > 0");

                            t.HasCheckConstraint("CK_LedgerEntries_BalanceAfterKobo_NonNegative", "[BalanceAfterKobo] >= 0");
                        });
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DestinationWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SourceWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Reference");

                    b.HasIndex("DestinationWalletId", "CreatedAtUtc");

                    b.HasIndex("SourceWalletId", "CreatedAtUtc");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_AmountKobo_Positive", "[AmountKobo] > 0");
                        });
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BalanceKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Wallets_BalanceKobo_NonNegative", "[BalanceKobo] >= 0");
                        });
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("NovaWallet.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NovaWallet.Domain.Entities.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.DailyTransferLimit", b =>
                {
                    b.HasOne("NovaWallet.Domain.Entities.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("NovaWallet.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NovaWallet.Domain.Entities.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NovaWallet.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("NovaWallet.Domain.Entities.Wallet", null)
                        .WithMany()
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NovaWallet.Domain.Entities.Wallet", null)
                        .WithMany()
                        .HasForeignKey("SourceWalletId")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
